### ISSUE TITLE
 unexpected errors

### ISSUE THREAD

**Issue by tiny-byte** [joshuavial/gulp-git-submodule#1]
Hi there
I just installed your module and made gulp file as instructed, but I get some unexpected errors!
when I run this command :
    	me@pc ~/myproject $ gulp sm:exec -c pwd

I get:

	{ [Function: exec] description: 'execute arbitrary commands in submodules' }
	[11:44:19] Using gulpfile ~/iform-fullstack/gulpfile.js
	[11:44:19] Starting 'sm:exec'...
	[11:44:19] 'sm:exec' errored after 52 ms
	[11:44:19] Error: Command failed: /bin/sh -c name=server/components/common && branch="$(git config -f ../.gitmodules submodule.$name.branch)" && pwd

how can I fix this?

**Comment by matthiasg** [comment]
similar to what i experience. 

when running a simple `gulp sm:list` i get:

```
iris-main >: gulp sm:list
{ [Function: exec] description: 'execute arbitrary commands in submodules' }
[20:34:55] Using gulpfile ~/Development/DockerTest/iris-main/gulpfile.js
[20:34:55] Starting 'sm:list'...
[20:34:56] 'sm:list' errored after 169 ms
[20:34:56] Error: Command failed:
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
[20:34:56] 'sm:list' errored after 172 ms
[20:34:56] Error: Command failed:
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
```

after upgrading to node 5.5.0 it says:

```
iris-main >: node -v
v5.5.0
iris-main >: gulp sm:list
{ [Function: exec] description: 'execute arbitrary commands in submodules' }
[20:44:29] Using gulpfile ~/Development/DockerTest/iris-main/gulpfile.js
[20:44:29] Starting 'sm:list'...
[20:44:30] 'sm:list' errored after 231 ms
[20:44:30] Error: Command failed: /bin/sh -c name=iris-docs-server && branch="$(git config -f ../.gitmodules submodule.$name.branch)" && printf $name

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
[20:44:30] 'sm:list' errored after 237 ms
[20:44:30] Error: Command failed: /bin/sh -c name=iris-server && branch="$(git config -f ../.gitmodules submodule.$name.branch)" && printf $name

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:821:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:469:12)
iris-main >:
```

this is on Mac 10.11.2
